"use client";

import { Navbar } from "@/components/layout/Navbar";
import { FadeIn } from "@/components/animations/FadeIn";
import { LegalDisclaimer } from "@/components/legal/LegalDisclaimer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white font-inter text-[#111111] selection:bg-[#111111] selection:text-white">
      <Navbar />
      
      <main className="max-w-4xl mx-auto px-6 pt-32 pb-24">
        <FadeIn>
          <div className="mb-16">
            <h1 className="text-5xl md:text-6xl font-black tracking-tight mb-4">Terms of Service</h1>
            <p className="text-zinc-500 font-bold uppercase tracking-widest text-xs">Last Updated: April 9, 2026</p>
          </div>

          {/* REQUIRED LEGAL SIGNAL */}
          <LegalDisclaimer />

          <div className="space-y-12 text-zinc-600 font-bold leading-extraloose">
            <section className="space-y-4">
              <h2 className="text-2xl font-black text-[#111111] tracking-tight">1. Agreement to Terms</h2>
              <p>
                By accessing or using Costly, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the service. Costly provides financial modeling tools; however, these tools are for simulation only and do not constitute professional advice.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-[#111111] tracking-tight">2. Financial Modeling Only</h2>
              <p>
                You acknowledge that the percentages, scores, and dollar amounts generated by Costly are estimates based on standard regional guidelines and user-inputted data. They are designed for financial scenario-modeling and are not guaranteed to reflect final legal outcomes or court mandates.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-[#111111] tracking-tight">3. Subscriptions & Payments</h2>
              <p>
                Access to premium features requires a valid payment. All fees are non-refundable unless otherwise specified by law or Stripe's platform policies. We reserve the right to modify pricing with prior notice.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-black text-[#111111] tracking-tight">4. Limitation of Liability</h2>
              <p>
                Costly and its creators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the modeling tools. All financial decisions should be verified independently with a certified financial planner or qualified attorney.
              </p>
            </section>
          </div>
        </FadeIn>
      </main>

      <footer className="border-t border-zinc-100 py-12 px-6">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-[10px] font-black uppercase tracking-widest text-zinc-400">© 2026 Costly – Professional Financial Modeling</p>
          <div className="flex gap-8">
             <a href="/" className="text-[10px] font-black uppercase tracking-widest text-[#111111] hover:text-zinc-500 transition-colors">Home</a>
             <a href="/privacy" className="text-[10px] font-black uppercase tracking-widest text-[#111111] hover:text-zinc-500 transition-colors">Privacy</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
